; this file will throw an error because it will consume too much memory
STR: .string "very very very very very very very very very very very  very very very very very  very very long string"
STR: .string "very very very very very very very very  very very long string"
STR2: .string "another very very very very very very very very long string"
STR3: .string "one more very very very very very very very very long string"
STR4: .string "very very very very very very very very  very very long string"
STR5: .string "another very very very very very very very very long string"
STR6: .string "one more very very very very very very very very long string"
STR7: .string "very very very very very very very very  very very long string"
STR8: .string "another very very very very very very very very long string"
STR9: .string "one more very very very very very very very very long string"
STR10: .string "very very very very very very very very  very very long string"
STR11: .string "another very very very very very very very very long string"
STR12: .string "one more very very very very very very very very long string"
STR13: .string "very very very very very very very very  very very long string"
STR14: .string "another very very very very very very very very long string"
STR15: .string "one more very very very very very very very very long string"
STR16: .string "very very very very very very very very  very very long string"
STR17: .string "another very very very very very very very very long string"
STR18: .string "one more very very very very very very very very long string"